In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
data = pd.read_csv('../datasource/fuelo_week_prices_2020_2025.csv')
data

      №           Седмица  Бензин A95  Дизел  Пропан Бутан
0     1  30.12 - 05.01.20        2.22   2.28          0.95
1     2  06.01 - 12.01.20        2.22   2.28          0.95
2     3  13.01 - 19.01.20        2.23   2.28          0.96
3     4  20.01 - 26.01.20        2.23   2.28          0.97
4     5  27.01 - 02.02.20        2.23   2.28          0.98
..   ..               ...         ...    ...           ...
369  49  01.12 - 07.12.25        2.43   2.50          1.12
370  50  08.12 - 14.12.25        2.43   2.50          1.12
371  51  15.12 - 21.12.25        2.43   2.49          1.12
372  52  22.12 - 28.12.25        2.42   2.47          1.13
373   1  29.12 - 04.01.26        1.75   1.78          0.82

[374 rows x 5 columns]

(374, 5)

In [6]:
data = data.drop_duplicates()

In [8]:
data.shape
data

      №           Седмица  Бензин A95  Дизел  Пропан Бутан
0     1  30.12 - 05.01.20        2.22   2.28          0.95
1     2  06.01 - 12.01.20        2.22   2.28          0.95
2     3  13.01 - 19.01.20        2.23   2.28          0.96
3     4  20.01 - 26.01.20        2.23   2.28          0.97
4     5  27.01 - 02.02.20        2.23   2.28          0.98
..   ..               ...         ...    ...           ...
369  49  01.12 - 07.12.25        2.43   2.50          1.12
370  50  08.12 - 14.12.25        2.43   2.50          1.12
371  51  15.12 - 21.12.25        2.43   2.49          1.12
372  52  22.12 - 28.12.25        2.42   2.47          1.13
373   1  29.12 - 04.01.26        1.75   1.78          0.82

[314 rows x 5 columns]

In [9]:
data.to_csv("cleaned_fuelo_data.csv", index=False, encoding="utf-8-sig")