In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv('../datasource/fuelo_week_prices_all.csv')
data

     №           Седмица  Бензин A95  Дизел  Пропан Бутан
0    1  30.12 - 05.01.20        2.22   2.28          0.95
1    2  06.01 - 12.01.20        2.22   2.28          0.95
2    3  13.01 - 19.01.20        2.23   2.28          0.96
3    4  20.01 - 26.01.20        2.23   2.28          0.97
4    5  27.01 - 02.02.20        2.23   2.28          0.98
..  ..               ...         ...    ...           ...
378  5  26.01 - 01.02.26        1.24   1.26          0.57
379  5  26.01 - 01.02.26        1.24   1.26          0.57
380  6  02.02 - 08.02.26        1.24   1.26          0.58
381  7  09.02 - 15.02.26        1.24   1.26          0.58
382  8  16.02 - 22.02.26        1.24   1.26          0.58

[383 rows x 5 columns]

In [3]:
data = data.drop_duplicates()

In [4]:
exchange_rate = 1.95583

#Извличаме годината от текста (последните 2 цифри)
data["year"] = data["Седмица"].str[-2:].astype(int) + 2000

#Избираме ценовите колони
price_cols = ["Бензин A95", "Дизел", "Пропан Бутан"]

#Конвертираме само до 2025
mask = data["year"] <= 2025
data.loc[mask, price_cols] = data.loc[mask, price_cols] / exchange_rate

# по желание закръгляне
data[price_cols] = data[price_cols].round(2)

In [5]:
# data.to_csv("cleaned_fuelo_data.csv", index=False, encoding="utf-8-sig")

In [6]:
data

     №           Седмица  Бензин A95  Дизел  Пропан Бутан  year
0    1  30.12 - 05.01.20        1.14   1.17          0.49  2020
1    2  06.01 - 12.01.20        1.14   1.17          0.49  2020
2    3  13.01 - 19.01.20        1.14   1.17          0.49  2020
3    4  20.01 - 26.01.20        1.14   1.17          0.50  2020
4    5  27.01 - 02.02.20        1.14   1.17          0.50  2020
..  ..               ...         ...    ...           ...   ...
377  4  19.01 - 25.01.26        1.24   1.26          0.59  2026
378  5  26.01 - 01.02.26        1.24   1.26          0.57  2026
380  6  02.02 - 08.02.26        1.24   1.26          0.58  2026
381  7  09.02 - 15.02.26        1.24   1.26          0.58  2026
382  8  16.02 - 22.02.26        1.24   1.26          0.58  2026

[321 rows x 6 columns]

In [7]:
data["start_date"] = (
    data["Седмица"].str.split(" - ").str[0]
)

data["start_date"] = pd.to_datetime(
    data["start_date"],
    format="%d.%m"
)

data["start_date"] = data.apply(
    lambda row: row["start_date"].replace(year=row["year"]),
    axis=1
)

data

     №           Седмица  Бензин A95  Дизел  Пропан Бутан  year start_date
0    1  30.12 - 05.01.20        1.14   1.17          0.49  2020 2020-12-30
1    2  06.01 - 12.01.20        1.14   1.17          0.49  2020 2020-01-06
2    3  13.01 - 19.01.20        1.14   1.17          0.49  2020 2020-01-13
3    4  20.01 - 26.01.20        1.14   1.17          0.50  2020 2020-01-20
4    5  27.01 - 02.02.20        1.14   1.17          0.50  2020 2020-01-27
..  ..               ...         ...    ...           ...   ...        ...
377  4  19.01 - 25.01.26        1.24   1.26          0.59  2026 2026-01-19
378  5  26.01 - 01.02.26        1.24   1.26          0.57  2026 2026-01-26
380  6  02.02 - 08.02.26        1.24   1.26          0.58  2026 2026-02-02
381  7  09.02 - 15.02.26        1.24   1.26          0.58  2026 2026-02-09
382  8  16.02 - 22.02.26        1.24   1.26          0.58  2026 2026-02-16

[321 rows x 7 columns]

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.isna().sum()

№               0
Седмица         0
Бензин A95      0
Дизел           0
Пропан Бутан    0
year            0
start_date      0
dtype: int64

In [10]:
data.dtypes

№                        int64
Седмица                    str
Бензин A95             float64
Дизел                  float64
Пропан Бутан           float64
year                     int64
start_date      datetime64[us]
dtype: object

In [12]:
data.describe()

,№,Бензин A95,Дизел,Пропан Бутан,year,start_date
count,321.000000,321.000000,321.000000,321.000000,321.000000,321
mean,26.034268,1.255701,1.284891,0.587819,2022.588785,2023-01-29 19:48:47.102803
min,1.000000,0.860000,0.880000,0.390000,2020.000000,2020-01-06 00:00:00
25%,13.000000,1.140000,1.160000,0.540000,2021.000000,2021-07-19 00:00:00
50%,26.000000,1.270000,1.270000,0.600000,2023.000000,2023-01-30 00:00:00
75%,39.000000,1.360000,1.410000,0.640000,2024.000000,2024-08-05 00:00:00
max,53.000000,1.750000,1.820000,0.820000,2026.000000,2026-12-29 00:00:00
std,15.291401,0.198172,0.226390,0.098210,1.772815,NaN

In [11]:
# data.to_csv(
#     "fuelo_master_dataset.csv",
#     index=False,
#     encoding="utf-8-sig"
# )